messages:
    start: "\n Привет! Так что же я умею?\n \nЯ умею работать с блокчейном, а именно - с nft коллекциями в блокчейне Solana!\n
    \nС моей помощью ты можешь узнать цену и объем популярных коллекции!\n \nЧуть позже я смогу искать параметры и тебе интересных nft коллекций!\n \nНо а сейчас, выбери интересующую тебя и нажми на кнопку))\n"
    choice: "Выбери коллекцию у которой хочешь узнать параметры!"
    mad_lads: "Mad Lads - одна из лучших комманд билдеров!"
    solcasino: "Одно из лучших и прозрачных казино на солане"
    lily: "Знаю я один цветок))"
    okay_bears: "Мишки которые сделали кого-то миллионером..."
