messages:
    start: "Приветосик"
    choice: "Выбери коллекцию у которой хочешь узнать параметры!"
    mad_lads: "Mad Lads - одна из лучших комманд билдеров!"
    solcasino: "Одно из лучших и прозрачных казино на солане"
    lily: "Знаю я один цветок))"
    okay_bears: "Мишки которые сделали кого-то миллионером..."
